FROM debian:jessie

MAINTAINER Erik Kastman, erik.kastman@gmail.com

ENV DEBIAN_FRONTEND noninteractive

# Add Additional System Utils
RUN apt-get update; \
    apt-get install -y openjdk-7-jre-headless file; \
    apt-get install -y gcc; \
    apt-get install -y make; \
    apt-get install -y unzip; \
    apt-get install -y wget; \
    apt-get install -y patch; \
    apt-get clean;

# Add Bio Utils
RUN apt-get install -y bioperl=1.6.924-1; \
    apt-get install -y mcl=1:14-137-1; \
    apt-get install -y phylip=1:3.696+dfsg-1; \
    apt-get install -y mafft=7.205-1; \
    apt-get clean;

WORKDIR /
COPY PGAP-1.12.tar.gz.md5 /PGAP-1.12.tar.gz.md5
RUN wget https://downloads.sourceforge.net/project/pgap/PGAP-1.12/PGAP-1.12.tar.gz; \
  md5sum -c PGAP-1.12.tar.gz.md5; \
  tar xzf PGAP-1.12.tar.gz; \
  mv /PGAP-1.12 /pgap

COPY updatePaths.patch /updatePaths.patch
RUN patch /pgap/PGAP.pl < /updatePaths.patch

RUN rm /PGAP-1.12.tar.gz /updatePaths.patch

RUN (echo y;echo o conf prerequisites_policy follow;echo o conf commit)|cpan; \
    cpan Bio::Phylo; \
    cpan Inline::C; \
    cpan Bio::AlignIO; \
    cpan Statistics::LineFit; \
    cpan Statistics::Distributions; \
